# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QQNews' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QQNews
  pod 'SwiftyJSON'
  #pod 'SnapKit', '~> 3.2.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'Alamofire', '~> 4.4'
  pod 'SDWebImage', '~> 4.0.0’
  pod 'MJRefresh', '~> 3.1.12'
  pod 'Realm', '~> 2.8.1'
  #pod 'RealmSwift'
	
end
